centos5:
  dockerfile: Dockerfile.centos5
  build: .
  command: cp -a /out/rbenv-ruby-2.4.1.tar.gz /tmp
  volumes:
    - .:/tmp:rw

centos6:
  dockerfile: Dockerfile.centos6
  build: .
  command: cp -a /out/rbenv-ruby-2.4.1.tar.gz /tmp
  volumes:
    - .:/tmp:rw

centos7:
  dockerfile: Dockerfile.centos7
  build: .
  command: cp -a /out/rbenv-ruby-2.4.1.tar.gz /tmp
  volumes:
    - .:/tmp:rw
